# Generated by Django 5.0 on 2023-12-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='Emp_address',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='Emp_phn',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='Emp_salary',
        ),
        migrations.AddField(
            model_name='emp',
            name='Emp_msg',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
