# Generated by Django 5.0 on 2023-12-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_emp_emp_address_remove_emp_emp_phn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=50)),
                ('i_email', models.EmailField(max_length=50)),
                ('i_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
